# Generated by Django 5.2.15 on 2026-06-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='projects/', verbose_name='Обложка')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Местоположение')),
                ('location_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Местоположение')),
                ('location_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Местоположение')),
                ('location_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Местоположение')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Год')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Наши работы',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('alt_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проекта',
                'ordering': ['order', 'id'],
            },
        ),
    ]
