# Generated by Django 5.2.15 on 2026-06-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, upload_to='certificates/files/', verbose_name='Файл (PDF)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, verbose_name='Номер')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Направление / подпись')),
                ('label_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Направление / подпись')),
                ('label_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Направление / подпись')),
                ('label_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Направление / подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TASHKENT PROFNASTIL SERVIS', max_length=200, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('address_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, max_length=150, verbose_name='Часы работы')),
                ('work_hours_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Часы работы')),
                ('work_hours_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Часы работы')),
                ('work_hours_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Часы работы')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('map_embed', models.TextField(blank=True, help_text='HTML-код встраиваемой карты (Яндекс/Google).', verbose_name='Карта (iframe / embed)')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram (Профнастил)')),
                ('instagram2', models.URLField(blank=True, verbose_name='Instagram (Сэндвич-панель)')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('about_text', models.TextField(blank=True, verbose_name='О компании')),
                ('about_text_ru', models.TextField(blank=True, null=True, verbose_name='О компании')),
                ('about_text_uz', models.TextField(blank=True, null=True, verbose_name='О компании')),
                ('about_text_en', models.TextField(blank=True, null=True, verbose_name='О компании')),
                ('process_text', models.TextField(blank=True, verbose_name='Технологический процесс')),
                ('process_text_ru', models.TextField(blank=True, null=True, verbose_name='Технологический процесс')),
                ('process_text_uz', models.TextField(blank=True, null=True, verbose_name='Технологический процесс')),
                ('process_text_en', models.TextField(blank=True, null=True, verbose_name='Технологический процесс')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('source_url', models.CharField(blank=True, max_length=300, verbose_name='Страница')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
