# Generated by Django 5.2.15 on 2026-06-24 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('step', models.CharField(blank=True, max_length=20, verbose_name='Шаг')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Диалог бота',
                'verbose_name_plural': 'Диалоги бота',
            },
        ),
    ]
