# Generated by Django 5.2.15 on 2026-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botdialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Основной номер, показываемый в верхней панели сайта.', max_length=40, verbose_name='Телефон в шапке'),
        ),
    ]
