# Generated by Django 5.2.15 on 2026-06-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('description_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Группа услуг',
                'verbose_name_plural': 'Группы услуг',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Изображение')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('alt_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображение услуги',
                'verbose_name_plural': 'Изображения услуги',
                'ordering': ['order', 'id'],
            },
        ),
    ]
