# Generated by Django 5.2.15 on 2026-06-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код RAL')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Название')),
                ('name_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(blank=True, max_length=80, null=True, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Название')),
                ('hex', models.CharField(help_text='#1166b3', max_length=7, verbose_name='HEX')),
            ],
            options={
                'verbose_name': 'Цвет (RAL)',
                'verbose_name_plural': 'Цвета (RAL)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('phone', models.CharField(blank=True, help_text='Например: +998 95 429-00-00', max_length=40, verbose_name='Телефон направления')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('main_image', models.ImageField(blank=True, upload_to='products/', verbose_name='Главное изображение')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='catalog.color', verbose_name='Доступные цвета')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('alt_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Характеристика')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Характеристика')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Характеристика')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Характеристика')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=200, null=True, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=200, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=200, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order', 'id'],
            },
        ),
    ]
